spring:
  application:
    name: service-pay

server:
  port: 8003

wechat-pay:
  #接下来两个用来标识用户
  #商户id
  merchant-id: xxxxxxxxxxx
  #公众号appid(和商户id绑定过)
  appid: xxxxxxxxxxx
  #接下来两个用来确保SSL(内容未作任何加密,只做了签名.)
  #商户证书序列号
  merchant-serial-number: xxxxxxxxxxx
  #商户私钥
  private-key: xxxxxxxxxxx
  #APIv3密钥(在微信支付回调通知和商户获取平台证书使用APIv3密钥)
  api-v3-key: xxxxxxxxxxx
  #接下来两个是相关地址
  #微信服务器地址
  domain: https://api.mch.weixin.qq.com
  #接收结果通知地址
  notify-domain: xxxxxxxxxxx
