server:
  port: 6379
spring:
  application:
    name: demo-redis
  redis:
    host: 121.
    port: 6277
    password: root123.
    timeout: 2000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 10
