server:
  port: 6379
spring:
  application:
    name: demo-redis
  redis:
    host: 121.
    port: 6277
    password: root123.
    timeout: 2000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 10
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        namespace: eb9c8339-989e-4689-9a0b-7949c02f05f2
        group: dev
        file-extension: yaml
        prefix: flag-service-dev
